# Use %PLAYER% to replace playername in broadcasts/messages

# Autorespawn enabled
auto-respawn-enabled: true
auto-respawn: 
  auto-respawn-message: '&b(!) You have just died. You will respawn in 10 seconds!'
  time: 5

# The message when the player dies
death-message: '&c(!) %PLAYER% has just died and has been put into Spectator Mode!'

# Should the plugin broadcast a message when the player dies
broadcast: true
broadcast-message: '&7%PLAYER% &cdied'

# Enable sounds when the player dies?
playsound: true
# Playsound has to be on to let a sound work. Use a sound of this site: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound: 'BLOCK_LAVA_EXTINGUISH'

# Send a effect when the player dies
effect-enabled: false
# Effect type
effect: 'HEART'

# Should the plugin send a command when the player dies?
death-command: false
death-commands:
  - 'spawn %PLAYER%'

# The message when the player respawned
respawn-message: '&b(!) You just respawned!'

# The respawn title and subtitle
respawn-title: '&cRespawned!'
respawn-subtitle: '&bDont die again'

# Respawn location (options: none, nearest-player, coordinates)
respawn-location: 'nearest-player'
## Only enabled if respawn-location is set to coordinates
locationx: 0.5
locationy: 70.0
locationz: 0.5

debug-mode: false
