name: Spectator-on-Death
author: Unprotesting
version: ${project.version}
main: unprotesting.com.github.Main
permissions:
    sod.gospectator:
        description: Allows you to go into spectator on death
        default: false
    sod.autorespawn:
        description: Allows you to respawn after death
        default: false